Update for reverse PRIME
pop-os/gnome-shell-extension-system76-power pull request #47
Opened 2020-06-30 16:35 UTC by crawfxrd

The 450.51 NVIDIA drivers finally implement support for reverse PRIME.
This allows using external displays while in hybrid graphics mode.

Requires: X server 1.20.7+

Ref: https://download.nvidia.com/XFree86/Linux-x86_64/450.51/README/randr14.html

2020-07-06 23:06 UTC, jacobgkau commented
As of today, the addw1 was able to use all of its external display ports while in Hybrid mode with 450.51.

On the oryp6, I was also able to get all three video ports working, although Mini DisplayPort and HDMI required plugging in multiple times (and running `xrandr` in one case) for the laptop to see the display.

2020-07-07 13:13 UTC, crawfxrd commented
Rebased and updated to also have the hotplug event switch to hybrid instead of NVIDIA.

2020-07-07 21:06 UTC, jacobgkau commented
This seems to be working fine on the gaze14.

I am still seeing touchy behavior with the oryp6. When I boot into Hybrid mode and plug in a display, the display seems to know that something's connected, but the Oryx does not output any video (no matter how many times I unplug/re-plug the cable) until I either run xrandr or open Settings -> Displays. When I do one of those things, I see these two lines appear in dmesg:

```
usb usb3: root hub lost power or was reset
usb usb4: root hub lost power or was reset
```

With HDMI, after those lines appear, the external display immediately starts working. With Mini DisplayPort or USB-C, after those lines appear, I still need to unplug the cable and plug it back in one more time before the external display starts working. In either case, once this has happened, I can unplug/re-plug and the external display continues working without issue. This behavior is not present in NVIDIA mode, or on the addw1 or gaze14.

2020-07-13 20:16 UTC, jacobgkau commented
With 50c88d2 on the oryp6, I can see that xrandr is running when I plug in an external display because the two `root hub lost power or was reset` lines appear in dmesg immediately when I plug the display in, without me having to run xrandr manually or open the display settings. However, the external display still doesn't come on until I unplug it and plug it in again (so hotplugging an external display currently requires plugging it in twice.)

This is the xrandr output after plugging in the display the first time, and after un-plugging and plugging it in the second time: 
[xrandr.txt](https://github.com/pop-os/gnome-shell-extension-system76-power/files/4914854/xrandr.txt)

Is it possible to have the display work the first time it's plugged in?

2020-07-13 20:20 UTC, leviport commented
From hybrid mode, we want to disable the "Switch to Nvidia" prompt when a display is connected, right? I still see it on gaze15. If I click "Continue using hybrid", the dialog does not appear again on subsequent display plug-ins.

When I hotplug a USB-C to DisplayPort display on the oryp6, it does not get detected. It did work when the display was attached during boot.

2020-07-13 20:30 UTC, crawfxrd commented
@jacobgkau it should. I have tested with HDMI and mDP. With HDMI, the display is detected automatically. With mDP, my monitor's input must be set to mDP for the oryp6 to recognize it.

@leviport are you using the correct build? This branch is still using `450.51` as the name, not `450.57`.

2020-07-13 20:35 UTC, leviport commented
> @leviport are you using the correct build? This branch is still using `450.51` as the name, not `450.57`.

Whoops, it looks like I missed that one on gaze15. I have both on this oryp6 though. I do not see the "Switch to Nvidia" prompt on gaze15 with the proper build added.

2020-07-13 23:06 UTC, jacobgkau commented
After additional testing, I'm definitely still seeing hotplug issues on the oryp6. It does seem to be somewhat intermittent. I have not seen HDMI affected by the issue today, just Mini DisplayPort and USB-C.

When the issue is happening, one port doesn't appear to affect the other ports; here's an example scenario:
- Boot Oryx Pro in Hybrid mode with display unplugged, set display to Mini DisplayPort.
- Plugged in Mini DisplayPort, display did not start working.
- Unplugged and re-plugged Mini DisplayPort, display started working.
- Unplugged Mini DislayPort, switched display from Mini DisplayPort input to USB-C input.
- Plugged in USB-C, display did not start working.
- Unplugged and re-plugged USB-C, display started working.

Here is a dmesg log of a boot where the issue did not occur (USB-C worked the first time I plugged it in): 
[dmesg-working.txt](https://github.com/pop-os/gnome-shell-extension-system76-power/files/4915574/dmesg-working.txt)

Here is a dmesg log of a boot where the issue did occur (USB-C didn't work the first time I plugged it in, but worked the second time): 
[dmesg-problem.txt](https://github.com/pop-os/gnome-shell-extension-system76-power/files/4915575/dmesg-problem.txt)

In the problem file, you can see where I plugged the display in the first time and it was detected as a USB device but not a display.

2020-09-18 20:28 UTC, leviport approved these changes
Good with the 455.23 beta driver: https://github.com/pop-os/nvidia-graphics-drivers/pull/57

2020-09-21 15:40 UTC, leviport requested changes
I just noticed a bug. In Compute mode, external displays still work, but attaching them summons the prompt to switch to hybrid mode.

2020-09-28 13:56 UTC, crawfxrd commented
Apparently caused by `xserver-xorg-video-nvidia-455`, which writes out the persistent file `/usr/share/X11/xorg.conf.d/10-nvidia.conf`. This package cannot be removed without also removing the NVIDIA drivers.

This presumptuous package is likely also causing me issues with pop-os/system76-power#57.

2020-09-28 14:01 UTC, jackpot51 commented
That package comes from our nvidia-graphics-drivers repo, so we could probably modify it's behavior

2020-10-02 21:54 UTC, merged